name: Build Windows Executable

on:
  push:
    branches: [ main, master, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name=QuickTextPro quicktext_pro.py
    
    - name: Get file info
      shell: bash
      run: |
        ls -lh dist/
        echo "File size: $(du -h dist/QuickTextPro.exe | cut -f1)"
    
    - name: Upload Windows Executable
      uses: actions/upload-artifact@v4
      with:
        name: QuickTextPro-Windows-${{ github.sha }}
        path: dist/QuickTextPro.exe
        retention-days: 30
    
    - name: Create Release (on tag push)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/QuickTextPro.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
